# Generated by Django 4.2.6 on 2023-10-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_timestamp_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
